# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2dc352eb093eeaa34039482010ec2d70fd6a325ed95127d5d9fa4c81d6c38c3a4c8ecb58d709356827d09e73eb5d624267608dde06ec0f923e7d5777b4719df8

test:
  secret_key_base: 325ad89de4bf9852a7123b4f2708be3e67bfc545d5a4f86467a4192dfb53dbe808558794ec63f701ba97acdf8a5912af05b91c74a2ea485ea5d84be245fba742

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
